plugins {
    id 'com.github.johnrengelman.shadow'
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    file("src/main/resources/pantographsandwires.accesswidener")

    forge {
        mixinConfig "pantographsandwires.mixins.json"
    }
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_version"

    modCompileOnly("dev.architectury:architectury-forge:${rootProject.architectury_api_version}")
    modImplementation(include("de.mrjulsen.mcdragonlib:dragonlib-forge:${rootProject.minecraft_version}-${rootProject.dragonlib_version}"))

    modImplementation("com.simibubi.create:create-${rootProject.minecraft_version}:${rootProject.create_forge_version}:slim") { transitive = false }
    modImplementation("net.createmod.ponder:Ponder-Forge-${rootProject.minecraft_version}:${rootProject.ponder_forge_version}")
    modCompileOnly("dev.engine-room.flywheel:flywheel-forge-api-${rootProject.minecraft_version}:${rootProject.flywheel_forge_version}")
    modRuntimeOnly("dev.engine-room.flywheel:flywheel-forge-${rootProject.minecraft_version}:${rootProject.flywheel_forge_version}")
    modImplementation("com.tterrag.registrate:Registrate:${rootProject.registrate_forge_version}")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation("io.github.llamalad7:mixinextras-forge:0.4.1")
    compileOnly("org.embeddedt:embeddium-${rootProject.minecraft_version}:${rootProject.embeddium_version}")

}